version: '3.9'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python vk_internship/manage.py runserver 0.0.0.0:8000
